### ISSUE TITLE
HELLO WORLD! SUCCESS!

### ISSUE THREAD

**Issue by negovan13** [openmainframeproject/cobol-programming-course#38] opened 2020-04-17 19:13 UTC
Well this is not an issue, but showing off a bit :D I just ran first COBOL program in my life and I am very excited! 🔢 👯 👯 🔢

**Comment by Dlthomass** [comment] 2020-04-17 22:04
just wake up to hear the news, so happy.

**Comment by MrGmaw** [comment] 2020-04-17 22:18
Hi mates, a good place to share our experience learning COBOL.

2. Questions and Help

We are using Slack for system access questions and password issues:
Click this link https://openmainframeproject.slack.com/ to add yourself to the Open Mainframe Project Slack workspace. Within this workspace, add the cobol-programming-course channel.

**Comment by Dlthomass** [comment] 2020-04-18 04:35
still stuck on chapter 4.6, connection does not work. Tried everything, still not passed. So frustrated

**Comment by Dlthomass** [comment] 2020-04-18 06:04
finally passed, thanks for your help @Scott Cosel. Any guys need help, please go to Slack, then message me if I noticed.

**Comment by cobol10** [comment] 2020-04-18 10:32
How did you connect?

**Comment by negovan13** [comment] 2020-04-18 10:41
Register here: http://ibm.biz/cobollabs
And follow pdf, in chapter 4.6 you will connect to the z/OS with credentials you received in mail, after registration. I haven't got ip addresses in mail, you should get it, just in case here you go:
IP address for VSCode extension: https://192.86.32.250:10443
IP address for TN3270: 192.86.32.250 Port 623
IP address for IDz: 192.86.32.250 Port 4035

**Comment by Dlthomass** [comment] 2020-04-18 10:42
> How did you connect?

Do u have your own ID and Password? then follow the PDF, I  2 troubles.  I have picture uploaded, which one you have?

**Comment by cobol10** [comment] 2020-04-18 13:21
Yes, I have ID and Password. But I don't understand how enter to Sign in to Open Mainframe Project

**Comment by sccosel** [comment] 2020-04-19 04:40
Did you follow the course instructions? https://github.com/openmainframeproject/cobol-programming-course/blob/master/COBOL%20Programming%20with%20VSCode.pdf  Page 37, 4.6 Lab 1 discusses connecting to the mainframe.  Wherever you see Z99998, be sure to use your own id, Z80xxx, not Z99998 as shown as an example in the guide.

**Comment by cobol10** [comment] 2020-04-19 04:57
I understand it.  I can't do the following from the instructions in a letter from IBM; "We are using Slack for system access questions and password issues:
Click this link to add yourself to the Open Mainframe Project Slack workspace. Within this workspace, add the cobol-programming-course channel."

**Comment by cobol10** [comment] 2020-04-19 05:01
I can't add myself to the Open Mainframe Project Slack workspace. Maybe someone has a video, how to do it correctly?

**Comment by sccosel** [comment] 2020-04-19 06:07
@cobol10 I went around and around, but it eventually worked. I don' remember now what combination worked.  Be sure to use "openmainframeproject" on https://slack.com/signin or whatever URL it takes you to.

**Comment by RageshAntony** [comment] 2020-04-19 08:51
Why COBOL based transactions processing servers not yet updated to modern languages like R , Julia etc ?

**Comment by cobol10** [comment] 2020-04-19 09:21
What for? COBOL does this better than any other language.

**Comment by RageshAntony** [comment] 2020-04-19 09:35
> What for? COBOL does this better than any other language.

How ? It's verbose first 

Does it support Functional programming like lambdas , High order functions etc ?

**Comment by cobol10** [comment] 2020-04-19 09:38
For transaction processing, it is an ideal programming language.

**Comment by cobol10** [comment] 2020-04-19 09:40
There is nothing superfluous in it.

**Comment by RageshAntony** [comment] 2020-04-19 09:48
> There is nothing superfluous in it.

WOW 

Actually I am  Android developer using Kotlin 

I tried to learn cobol for fun after hearing that USA employment registration server overload

But it seems to be very verbose lot of typting .. that's why I am asking ?

This is my first COBOL program ::

            
            
            IDENTIFICATION DIVISION.
            PROGRAM-ID. VERBS.
            DATA DIVISION.
              WORKING-STORAGE SECTION.
              *> numbers we will perform operations on
              *> with verbs
              01 YOB PIC 9(4) VALUE 1993. *>  YOB = 1993;
              01 CUR PIC 9(4) VALUE 2020. *>  CUR = 2020;
              01 RES-AGE PIC 9(2). *> int RES-AGE;
              01 RES-QOT PIC 9(9).
              01 RES-REM PIC 9(9).
              01 RES-FCNT PIC 9(9).
              01 RES-LCNT PIC 9(9).
              01 RES-TOTCNT PIC 9(9).
              01 FNAME PIC A(15) VALUE 'RAGESH'.
              01 LNAME PIC A(15) VALUE 'ANTONY'.
             
            
            PROCEDURE DIVISION.
              
              COMPUTE RES-AGE = (CUR - YOB).
              
              INSPECT FNAME TALLYING RES-FCNT FOR CHARACTERS.
              INSPECT LNAME TALLYING RES-LCNT FOR CHARACTERS.
              COMPUTE RES-TOTCNT = (RES-FCNT + RES-LCNT).
              DIVIDE  YOB BY RES-TOTCNT GIVING RES-QOT REMAINDER RES-REM.
              *> subtract YOB from CUR store result in res-age
              
              DISPLAY "NAME: "FNAME
            
              DISPLAY "Born In:"YOB
              DISPLAY "Current Year:"CUR
             
              DISPLAY "AGE:"RES-AGE
              DISPLAY "TOT:"RES-TOTCNT
              DISPLAY "QOT:"RES-QOT
              DISPLAY "REM:"RES-REM
              
              
              IF RES-REM = 0
                DISPLAY "Can Vote"
              ELSE
                DISPLAY "cannot vote"
              END-IF.
              
             
              STOP RUN.

**Comment by sccosel** [comment] 2020-04-19 13:58
@RageshAntony And, did you run it?  Have you read or followed the class materials? The class materials explained that even non-programmers can follow the logic (of a working program), like IT auditors. Auditing programs is a necessary function of a financial audit perform by a large accounting firm of a publicly traded company to certify the accuracy of the company’s financial statements. The Cobol language was designed for transactional business data processing. It was never intended to be used for Android development, for example. If you need scientific functions, Cobol is probably not the best choice of language. However, Cobol has many built-in functions, or it can call another program, written in another language, like Fortran (a scientific language which was used to make the precise calculations necessary to send astronauts to the moon), or it can call numerous functions/subroutines in IBM’s Language Environment (LE). These same LE common subroutines can be called from many of IBM’s supported languages.  So, keep an open mind, follow the class materials and remember, different languages are best suited for the types of problems they were originally designed to solve. Enjoy the wonderful world of Cobol!

**Comment by RageshAntony** [comment] 2020-04-19 14:19
> @RageshAntony And, did you run it? Have you read or followed the class materials? The class materials explained that even non-programmers can follow the logic (of a working program), like IT auditors. Auditing programs is a necessary function of a financial audit perform by a large accounting firm of a publicly traded company to certify the accuracy of the company’s financial statements. The Cobol language was designed for transactional business data processing. It was never intended to be used for Android development, for example. If you need scientific functions, Cobol is probably not the best choice of language. However, Cobol has many built-in functions, or it can call another program, written in another language, like Fortran (a scientific language which was used to make the precise calculations necessary to send astronauts to the moon), or it can call numerous functions/subroutines in IBM’s Language Environment (LE). These same LE common subroutines can be called from many of IBM’s supported languages. So, keep an open mind, follow the class materials and remember, different languages are best suited for the types of problems they were originally designed to solve. Enjoy the wonderful world of Cobol!

Yeah I executed it 

You cleared bu doubt . I thought cobol is a Data Science language like R , but transaction processing is good in cobol ..

OK .

One question ? what is the difference between gnuCOBOL and IBM COBOL ?

**Comment by sccosel** [comment] 2020-04-19 15:20
@RageshAntony Here is a major difference:
1) gnuCOBOL is open source. Is it reliable? Is it certified by any one or entity? Are there any unknown or unreported compiler errors lurking about?
(Enterprise) IBM COBOL is a commercial paid product offering. The full faith of the IBM Corporation stands behind it, and a version of IBM COBOL has been offered for licensed for use for at least 50+ years!  Large institutions (e.g. publicly traded companies), especially where large monetary/financial transactions are involved, rely on the maturity of IBM COBOL to be free of compiler errors, that could be costly if undetected for any period of time. IBM does not publish the compiler source code, so there is no way for a customer’s programmer (of a licensee) to change the compiler, for any reason. This is a definite advantage, in the scope of a financial audit of a publicly traded company performed by a large accounting firm, performing such an audit to ensure the accuracy of a company’s financial statements.
2) Enterprise IBM COBOL is designed to run in an IBM mainframe environment, with the I/O custom to that environment.
I believe gnuCOBOL is designed to run in non-IBM controlled environments, so the I/O will be different.  Other than I/O, the language capabilities and syntax should be similar.

Hope that helped!

**Comment by RageshAntony** [comment] 2020-04-19 15:30
> @RageshAntony Here is a major difference:
> 
> 1. gnuCOBOL is open source. Is it reliable? Is it certified by any one or entity? Are there any unknown or unreported compiler errors lurking about?
>    (Enterprise) IBM COBOL is a commercial paid product offering. The full faith of the IBM Corporation stands behind it, and a version of IBM COBOL has been offered/licensed for use for at least 50+ years!  Large institutions (e.g. publicly traded companies), especially where large monetary/financial transactions are involved, rely on the maturity of IBM COBOL to be free of compiler errors, that could be costly if undetected for any period of time. IBM does not publish the compiler source code, so there is no way for a customer’s programmer (of a licensee) to change the compiler, for any reason. This is a definite advantage, in the scope of a financial audit of a publicly traded company performed by a large accounting firm, performing such an audit to ensure the accuracy of a company’s financial statements.
> 2. Enterprise IBM COBOL is designed to run in an IBM mainframe environment, with the I/O custom to that environment.
>    I believe gnuCOBOL is designed to run in non-IBM controlled environments, so the I/O will be different.  Other than I/O, the language capabilities and syntax should be similar.
> 
> Hope that helped!

And ... Is  it possible to run IBM COBOL in desktop linux OS ? Are only mainframe is needed ?

**Comment by sccosel** [comment] 2020-04-19 15:41
@RageshAntony IBM COBOL is a PAID, licensed product offering from IBM. It is probably not designed to run on desktop Linux, plus legally, you would need to license it from IBM. They do not give it away for free, and do not publish the source code.

**Comment by RageshAntony** [comment] 2020-04-19 15:46
> @RageshAntony IBM COBOL is a PAID, licensed product offering from IBM. It is probably not designed to run on desktop Linux, plus legally, you would need to license it from IBM. They do not give it away for free, and do not publish the source code.

thank you . you cleared lot of doubts .

**Comment by comps3** [comment] 2020-04-20 01:11
> We are using Slack for system access questions and password issues:
> Click this link https://openmainframeproject.slack.com/ to add yourself to the Open Mainframe Project Slack workspace. Within this workspace, add the cobol-programming-course channel.

This link worked for me to get added to the workspace: [Slack workspace signup](https://slack.openmainframeproject.org/)

**Comment by RageshAntony** [comment] 2020-04-21 16:18
> @RageshAntony And, did you run it? Have you read or followed the class materials? The class materials explained that even non-programmers can follow the logic (of a working program), like IT auditors. Auditing programs is a necessary function of a financial audit perform by a large accounting firm of a publicly traded company to certify the accuracy of the company’s financial statements. The Cobol language was designed for transactional business data processing. It was never intended to be used for Android development, for example. If you need scientific functions, Cobol is probably not the best choice of language. However, Cobol has many built-in functions, or it can call another program, written in another language, like Fortran (a scientific language which was used to make the precise calculations necessary to send astronauts to the moon), or it can call numerous functions/subroutines in IBM’s Language Environment (LE). These same LE common subroutines can be called from many of IBM’s supported languages. So, keep an open mind, follow the class materials and remember, different languages are best suited for the types of problems they were originally designed to solve. Enjoy the wonderful world of Cobol!

If a Java/.Net/NodeJS .... developer who don't know anything about COBOL , Mainframes and Transaction processing ...

Starts to learn all the above 3 , Do he able to get JOBs with future security and decent salary ?

**Comment by sccosel** [comment] 2020-04-21 16:59
@RageshAntony You posted the same thing, 3 times. You might consider deleting the last 2.  As far as marketability, the more overall software experience you have in different languages/operating systems (Windows, Unix, Linux, z/OS) in addition to Cobol, should be a plus for anyone looking to get hired.  Start here: https://forms.business.nj.gov/tech/

**Comment by RageshAntony** [comment] 2020-04-24 07:37
> @RageshAntony IBM COBOL is a PAID, licensed product offering from IBM. It is probably not designed to run on desktop Linux, plus legally, you would need to license it from IBM. They do not give it away for free, and do not publish the source code.

In the Course document , it seems to be the COBOL program will be submitted to a z/OS system and JOB output will be returned ?

The course also states that it deals with Enterprise COBOL and as you said it runs only in mainframe .

That means do I need a mainframe to learn the course !!!!.

Please assist me 

(I runned my above code using gnuCOBOL only)

**Comment by sccosel** [comment] 2020-04-24 08:13
@RageshAntony - You can get free credentials to run your program on a mainframe. My suggestion is you follow these instructions, STEP by STEP: https://github.com//cobol-programming-course/issues/53

**Comment by MikeBauerCA** [comment] 2021-12-06 13:50
Awesome to hear of this early success, closing as no action is required here.

**Closed by MikeBauerCA** 2021-12-06 13:50 UTC
Labels: discussion
