### ISSUE TITLE
Real World issues for a new COBOL learner ?

### ISSUE THREAD

**Issue by RageshAntony** [openmainframeproject/cobol-programming-course#83] opened 2020-04-27 06:01 UTC
I like IBMs work in bringing COBOL to other developers 

But  I want to discuss about some issues 

** issues** 

1) Work directly on Mission Critical COBOL code without getting prior experience. That is , When  a person starts as a fresher , he will get  experience by working in small software companies who develop smaller apps.Then ,he will migrate to big companies who handles large project.But In COBOL , there is no chance for that .none of the small and medium level companies don't develop any COBOL based systems .Only Big companies running COBOL , and all of them are mission critical code that should be handled by experienced people .So how a developer able to get real world experience in COBOL before going to big companies  ?

2) COBOL's community support is very low. It's difficult to get a immediate help from a friend in COBOL issue by calling him by phone , since there is low possibility of having experienced COBOL developer as a friend because  experienced COBOL developers are 2 generations above from modern "born in 90s" generation .  

3) Non Openness . The IBM Enterprise COBOL is locked inside mainframes and there is no way to run the code in home system Even though IBM mainframe access is free and also good , it's not that much practical to learn without having access to the whole system . He must have internet connection etc . And running a high quality code by a developer in this free main frame access in not possible .For example , I ran 14 GB ram consuming python ML code that ran for 2 hours in my Home PC without any problem . How can a developer explore the same scenario in this mainframe access ?

4) Practically useless gnuCOBOL .    One can use gnuCOBOL to avoid above 2nd point issue . But gnuCOBOL is having many differences when compared to IBM COBOL and no companies using gnuCOBOL in any real world mission critical code .

5) One need to learn JCL and mainframe ecosystem to learn COBOL , None the language I know such as Java,Kotlin, Javascript , Dart don't have this type of issue.

6) Jobs . COBOL having very less job listing when searching in job sites like Naukri , Indeed etc

Please tell you views

**Comment by sccosel** [comment] 2020-04-27 15:12
@RageshAntony - I'm sure Cobol shops like The State of NJ, still have a (large) number of Cobol developers/system engineers, even though they have a need for more.  You are trying to run, before you walk.  You may be a senior level develper in the languages you already know, but it will take a little time to develop senior level Cobol skills.  Consider that every IT request for service from a user is not a senior level task.  This is how I learned Cobol in the 1980's.  Non-senior level tasks can be performed by developers with non-senior level skills, such as creating reports or creating files that can be used by subsequent processes.  Yes, you would probably need more direction and narrower tasks in the beginning, writing Cobol, but as you gain experience in the language, tasks assigned to you would get more challenging.  You have a definite advantage knowing other languages and methods at a senior level.  How long did it take you to learn those, well?  So, my point is, even though you would not be immediately thrown on the front line, your presence in a company (or government entity) would free up the senior level developers from having to perform non-senior level tasks, which would allow them to concentrate on the most critical tasks at hand.  That is good for you too, because who needs that much stress, when you don't feel fully confident, yet.  You'll get there, it just takes time.  And this community (on Slack too) is a great place to pose "How to" questions.  Once hired, you will be surrounded by colleagues more knowledgable in Cobol than yourself, who you can learn from.  And, just reviewing already running code is a great way to learn.  To become an expert, in anything, takes time, effort and practice.  And, by the way, I was born in the 1960's, not 1990's!  Best of luck to you!

**Comment by RageshAntony** [comment] 2020-04-27 15:19
> @RageshAntony - I'm sure Cobol shops like The State of NJ, still have a (large) number of Cobol developers/system engineers, even though they have a need for more. You are trying to run, before you walk. You may be a senior level develper in the languages you already know, but it will take a little time to develop senior level Cobol skills. Consider that every IT request for service from a user is not a senior level task. This is how I learned Cobol in the 1980's. Non-senior level tasks can be performed by developers with non-senior level skills, such as creating reports or creating files that can be used by subsequent processes. Yes, you would probably need more direction and narrower tasks in the beginning, writing Cobol, but as you gain experience in the language, tasks assigned to you would get more challenging. You have a definite advantage knowing other languages and methods at a senior level. How long did it take you to learn those, well? So, my point is, even though you would not be immediately thrown on the front line, your presence in a company (or government entity) would free up the senior level developers from having to perform non-senior level tasks, which would allow them to concentrate on the most critical tasks at hand. That is good for you too, because who needs that much stress, when you don't feel fully confident, yet. You'll get there, it just takes time. And this community (on Slack too) is a great place to pose "How to" questions. Once hired, you will be surrounded by colleagues more knowledgable in Cobol than yourself, who you can learn from. And, just reviewing already running code is a great way to learn. To become an expert, in anything, takes time, effort and practice. And, by the way, I was born in the 1960's, not 1990's! Best of luck to you!

Wonderful answer . Thanks 

also tell you views about the 3rd and 5th point ?

**Comment by sccosel** [comment] 2020-04-27 16:27
@RageshAntony
3) You are trying to relate your current knowledge and job assignments to Cobol.  Relax.  IBM is providing you with a unique opportunity, offering free mainframe "computer time" on a real (not emulated one as confirmed by @paulnewt) IBM Mainframe (probably located in Dallas, TX).  Use this OPPORTUNITY to learn the basic foundations of COBOL, JCL, TSO/ISPF, DFSORT/ICETOOL, DB2 (if available), etc. etc. etc.  There are plenty of videos, online and paid classes that you can take, and use the mainframe access IBM is providing, to learn them all.  Consider taking IBM's free, Master the Mainframe course.  I think the 2019 version is still available.  Sign up and go through that while the 2020 course is being prepared to launch.  Again, ask lots of questions, especially on the Slack Channel!

4) As long as you have access to an IBM mainframe as mentioned in #3, above, forget about gnuCOBOL for now.  You've got access to the latest, most up to date version, from IBM!

5) See #3.  All of the basic mainframe ecosystem is available to you NOW.  Take advantage of it!  You are your own, best instructor!

Best of luck to you!

**Closed** 2020-05-02 13:47 UTC

**Comment by paulnewt** [comment] 2020-05-02 13:48
Acknowledged --- Part 4 to include advanced topics is under consideration - JCL as it relates to COBOL and compiler options are 2 of the many topics on our radar
