### ISSUE TITLE
Chapters link is 404 on Readme.md

### ISSUE THREAD

**Issue by bolaurent** [openmainframeproject/cobol-programming-course#19] opened 2020-04-14 21:34 UTC
This link is 404

![image](https://user-images.githubusercontent.com/1839790/79276531-0e962280-7e5d-11ea-9340-849c5ec88418.png)

**Comment by camdroid** [comment] 2020-04-14 22:03
I think this is a duplicate of #11.

**Comment by Sudharsana-Srinivasan** [comment] 2020-04-15 01:55
Will update the link to point to the Course pdf

**Comment by martinkeen** [comment] 2020-04-15 02:38
Thank you. Fixed.

**Closed by martinkeen** 2020-04-15 02:38 UTC
